spring.application.name=DoaCesta

spring.datasource.url=${SUPABASE_URL}
spring.datasource.username=${SUPABASE_USERNAME}
spring.datasource.password=${SUPABASE_PASSWORD}

supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
